const assetRoot = "/sites/cafecomdeuspai-com-8456844d/root-8a5edab2";

export type ProductCategory = "Lançamento" | "Destaques" | "Imperdível";

export type CatalogProduct = {
  slug: string;
  name: string;
  priceCents: number;
  price: string;
  originalPrice: string | null;
  installment: string;
  image: string;
  category: ProductCategory;
  description: string;
  sku: string;
};

export const PRODUCTS = [
  {
    slug: "cafe-com-deus-pai-vol-6-brochura-a-vida-que-voce-busca-esta-na-cura-que-voce-precisa",
    name: "Café com Deus Pai vol.6 (brochura) + A vida que você busca está na cura que você precisa",
    priceCents: 9990,
    price: "R$99,90",
    originalPrice: "R$181,80",
    installment: "4 de R$24,98",
    image: `${assetRoot}/asset-006.webp`,
    category: "Imperdível",
    description: "Dois livros para transformar sua rotina de fé: o devocional Café com Deus Pai volume 6, em edição brochura, e A vida que você busca está na cura que você precisa.",
    sku: "CCDP-COMBO-LIVROS-006",
  },
  {
    slug: "cafe-com-deus-pai-vol-6-brochura-a-vida-que-voce-busca-esta-na-cura-que-voce-precisa-caneca",
    name: "Café com Deus Pai vol.6 (brochura) + A vida que você busca está na cura que você precisa + caneca",
    priceCents: 21990,
    price: "R$219,90",
    originalPrice: "R$351,70",
    installment: "4 de R$54,98",
    image: `${assetRoot}/asset-007.webp`,
    category: "Imperdível",
    description: "Combo com os livros Café com Deus Pai volume 6 e A vida que você busca está na cura que você precisa, acompanhado de uma caneca exclusiva.",
    sku: "CCDP-COMBO-LIVROS-CANECA-006",
  },
  {
    slug: "2-canecas-cafe-com-deus-pai-vol-6",
    name: "2 canecas Café com Deus Pai (vol.6)",
    priceCents: 19990,
    price: "R$199,90",
    originalPrice: "R$259,80",
    installment: "4 de R$49,98",
    image: `${assetRoot}/asset-008.webp`,
    category: "Imperdível",
    description: "Conjunto com duas canecas da coleção Café com Deus Pai volume 6, ideal para compartilhar seus momentos de pausa e devoção.",
    sku: "CCDP-2-CANECAS-006",
  },
  {
    slug: "a-vida-que-voce-busca-esta-na-cura-que-voce-precisa-lata-alfajor-velutti-com-6-un-marca-texto",
    name: "A vida que você busca está na cura que você precisa + Lata Alfajor Velutti com 6 un + marca-texto",
    priceCents: 14990,
    price: "R$149,90",
    originalPrice: "R$169,70",
    installment: "4 de R$37,48",
    image: `${assetRoot}/asset-009.webp`,
    category: "Imperdível",
    description: "Kit presenteável com o livro A vida que você busca está na cura que você precisa, lata com seis alfajores Velutti e marca-texto.",
    sku: "AVQVB-COMBO-ALFAJOR-MT",
  },
  {
    slug: "a-vida-que-voce-busca-esta-na-cura-que-voce-precisa-planner-marca-texto",
    name: "A vida que você busca está na cura que você precisa + Planner + marca-texto",
    priceCents: 12990,
    price: "R$129,90",
    originalPrice: "R$174,70",
    installment: "4 de R$32,48",
    image: `${assetRoot}/asset-012.webp`,
    category: "Destaques",
    description: "Combo para leitura e organização com o livro A vida que você busca está na cura que você precisa, planner e marca-texto.",
    sku: "AVQVB-COMBO-PLANNER-MT",
  },
  {
    slug: "planner-cafe-com-deus-pai-2025",
    name: "Planner Café com Deus Pai",
    priceCents: 5990,
    price: "R$59,90",
    originalPrice: "R$126,90",
    installment: "4 de R$14,98",
    image: `${assetRoot}/asset-013.webp`,
    category: "Destaques",
    description: "Planner Café com Deus Pai para organizar compromissos, planos e momentos de reflexão ao longo do ano.",
    sku: "CCDP-PLANNER-2025",
  },
  {
    slug: "a-vida-que-voce-busca-esta-na-cura-que-voce-precisa-cafe-com-deus-pai-brochura-vol-6-planner",
    name: "A vida que você busca está na cura que você precisa + Café com Deus Pai (brochura) vol.6 + Planner",
    priceCents: 17990,
    price: "R$179,90",
    originalPrice: "R$271,70",
    installment: "4 de R$44,98",
    image: `${assetRoot}/asset-014.webp`,
    category: "Destaques",
    description: "Kit completo com dois livros — A vida que você busca está na cura que você precisa e Café com Deus Pai volume 6 — mais um planner.",
    sku: "CCDP-COMBO-2L-PLANNER-006",
  },
  {
    slug: "2-livros-cafe-com-deus-pai-vol-6-brochura-2-canecas",
    name: "2 livros Café com Deus Pai vol. 6 (brochura) + 2 canecas",
    priceCents: 28990,
    price: "R$289,90",
    originalPrice: "R$483,60",
    installment: "4 de R$72,48",
    image: `${assetRoot}/asset-015.webp`,
    category: "Destaques",
    description: "Combo para duas pessoas com dois exemplares em brochura de Café com Deus Pai volume 6 e duas canecas da coleção.",
    sku: "CCDP-COMBO-2L-2C-006",
  },
  {
    slug: "combo-cafe-com-deus-pai-vol-6-brochura-lata-de-cafe-gourmet",
    name: "Combo: Café com Deus Pai vol.6 (brochura) + Lata de café gourmet",
    priceCents: 10890,
    price: "R$108,90",
    originalPrice: "R$161,80",
    installment: "4 de R$27,23",
    image: `${assetRoot}/asset-017.webp`,
    category: "Imperdível",
    description: "O devocional Café com Deus Pai volume 6, em edição brochura, acompanhado de uma lata de café gourmet.",
    sku: "CCDP-COMBO-CAFE-006",
  },
  {
    slug: "combo-cafe-com-deus-pai-2026-brochura-ecobag-copo-250ml",
    name: "Combo Café com Deus Pai vol.6 (brochura) + Ecobag + Copo (250ml)",
    priceCents: 9990,
    price: "R$99,90",
    originalPrice: "R$161,70",
    installment: "4 de R$24,98",
    image: `${assetRoot}/asset-018.webp`,
    category: "Imperdível",
    description: "Combo Café com Deus Pai com livro volume 6 em brochura, ecobag exclusiva e copo de 250 ml.",
    sku: "CCDP-COMBO-ECOBAG-COPO-006",
  },
  {
    slug: "cafe-com-deus-pai-2026-brochura-10-filtros-individuais",
    name: "Café com Deus Pai vol.6 (brochura) + 10 filtros individuais",
    priceCents: 7890,
    price: "R$78,90",
    originalPrice: "R$146,80",
    installment: "4 de R$19,73",
    image: `${assetRoot}/asset-019.webp`,
    category: "Imperdível",
    description: "Livro Café com Deus Pai volume 6, em edição brochura, acompanhado de dez filtros individuais de café.",
    sku: "CCDP-COMBO-10-FILTROS-006",
  },
  /* ---- Lançamento 2027 (vol.7) ----
     Importados do catálogo oficial. As páginas de produto, a vitrine da
     home e a busca saem daqui automaticamente: PRODUCTS alimenta os três. */
  {
    slug: "cafe-com-deus-pai-vol-7-brochura",
    name: "Café com Deus Pai vol.7 (brochura) | porções diárias de restauração",
    priceCents: 7990,
    price: "R$79,90",
    originalPrice: null,
    installment: "4 de R$19,98",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-brochura-2c2baa.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Na correria diária, sua alma clama por um instante de paz e direção. A resposta que você tanto procura pode estar em um simples café com Deus Pai! O Volume 7 chega com 365 novas mensagens, uma para cada dia do ano, para acompanhar sua rotina e convidá-lo a viver uma experiência única: parar, abrir ",
    sku: "CCDP-2027-001",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-capa-dura-copo-250ml",
    name: "Café com Deus Pai vol. 7 (capa dura) + copo 250 ml",
    priceCents: 8990,
    price: "R$89,90",
    originalPrice: null,
    installment: "4 de R$22,48",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-capa-dura-copo-250ml-c6ed40.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Neste combo você recebe o livro Café com Deus Pai - Volume 7, na versão capa dura. São 365 novas mensagens, uma para cada dia do ano, para acompanhar sua rotina e convidar você a viver essa experiência diariamente. E para completar esse momento, o combo acompanha um copo para café de 250 ml, produz",
    sku: "CCDP-2027-002",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-capa-dura-marca-texto",
    name: "Café com Deus Pai vol. 7 (capa dura) + marca-texto",
    priceCents: 8990,
    price: "R$89,90",
    originalPrice: null,
    installment: "4 de R$22,48",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-capa-dura-marca-texto-8695ac.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Neste combo você recebe o livro Café com Deus Pai - Volume 7, na versão capa dura. São 365 novas mensagens, uma para cada dia do ano, para acompanhar sua rotina, fortalecer sua fé e trazer novas perspectivas para os seus dias. Uma jornada de encontros, reflexões e experiências extraordinárias esper",
    sku: "CCDP-2027-003",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-brochura-livro-de-oracao-verde",
    name: "Café com Deus Pai vol. 7 (brochura) + livro de oração (verde)",
    priceCents: 11990,
    price: "R$119,90",
    originalPrice: null,
    installment: "4 de R$29,98",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-brochura-livro-de-oracao-verde-57ec5a.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Neste combo você recebe o Café com Deus Pai Volume 7, na versão brochura. São 365 novas mensagens, uma para cada dia do ano, para acompanhar sua rotina, fortalecer sua fé e trazer direção para os seus dias. E para complementar esse momento, o combo acompanha o Livro de Oração na cor Verde, com uma ",
    sku: "CCDP-2027-004",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-brochura-filtro-de-cafe",
    name: "Café com Deus Pai vol. 7 (brochura) + filtro de café",
    priceCents: 7990,
    price: "R$79,90",
    originalPrice: null,
    installment: "4 de R$19,98",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-brochura-filtro-de-cafe-d84bd8.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Transforme seu momento de leitura em uma experiência ainda mais especial. Neste combo você recebe o livro Café com Deus Pai - Volume 7 na versão brochura. São 365 novas mensagens, uma para cada dia do ano, convidando você a desacelerar, abrir o coração e viver momentos de fé, reflexão e intimidade ",
    sku: "CCDP-2027-005",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-brochura-caderno-de-anotacoes-marca-texto",
    name: "Café com Deus Pai vol. 7 (brochura) + caderno de anotações + marca-texto",
    priceCents: 10490,
    price: "R$104,90",
    originalPrice: null,
    installment: "4 de R$26,23",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-brochura-caderno-de-anotacoes-marca--8dc6fe.jpg",
    category: "Lançamento",
    description: "Descrição do Produto O combo inclui o livro Café com Deus Pai Volume 7, na versão brochura, o Caderno de Anotações, pensado para registrar aprendizados, reflexões e tudo o que Deus falar com você, além de um marca-texto para destacar mensagens e versículos importantes. Leia, marque e guarde cada aprendizado. Detalhes: ",
    sku: "CCDP-2027-006",
  },
  {
    slug: "livro-de-oracao-cafe-com-deus-pai-marrom",
    name: "Livro de oração Café com Deus Pai | marrom",
    priceCents: 5290,
    price: "R$52,90",
    originalPrice: null,
    installment: "4 de R$13,23",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/livro-de-oracao-cafe-com-deus-pai-marrom-5c85f1.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Um momento de oração para acompanhar cada dia do ano. Este livro foi pensado para ser o complemento perfeito ao seu devocional, ajudando você a transformar a reflexão do dia em um momento de conversa e intimidade com Deus Pai. Com uma oração para cada dia, você encontrará palavras para fortalecer s",
    sku: "CCDP-2027-007",
  },
  {
    slug: "livro-de-oracao-cafe-com-deus-pai-verde",
    name: "Livro de oração Café com Deus Pai | verde",
    priceCents: 5290,
    price: "R$52,90",
    originalPrice: null,
    installment: "4 de R$13,23",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/livro-de-oracao-cafe-com-deus-pai-verde-ed290c.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Um momento de oração para acompanhar cada dia do ano. Este livro foi pensado para ser o complemento perfeito ao seu devocional, ajudando você a transformar a reflexão do dia em um momento de conversa e intimidade com Deus Pai. Com uma oração para cada dia, você encontrará palavras para fortalecer s",
    sku: "CCDP-2027-008",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-brochura-livro-de-oracao-marrom-marca-texto",
    name: "Café com Deus Pai vol. 7 (brochura) + livro de oração (marrom) + marca-texto",
    priceCents: 12990,
    price: "R$129,90",
    originalPrice: null,
    installment: "4 de R$32,48",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-brochura-livro-de-oracao-marrom-marc-fc4499.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Neste combo você recebe o livro Café com Deus Pai - Volume 7, na versão brochura. São 365 novas mensagens, uma para cada dia do ano, para acompanhar sua rotina e trazer fé, direção e novas perspectivas para os seus dias. Depois da leitura, continue esse momento com o Livro de Oração na cor Marrom, ",
    sku: "CCDP-2027-009",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-brochura-livro-de-oracao-verde-marca-texto",
    name: "Café com Deus Pai vol. 7 (brochura) + livro de oração (verde) + marca-texto",
    priceCents: 12990,
    price: "R$129,90",
    originalPrice: null,
    installment: "4 de R$32,48",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-brochura-livro-de-oracao-verde-marca-29c6f3.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Neste combo você recebe o livro Café com Deus Pai - Volume 7, na versão brochura. São 365 novas mensagens, uma para cada dia do ano, para acompanhar sua rotina e trazer fé, direção e novas perspectivas para os seus dias. Depois da leitura, continue esse momento com o Livro de Oração na cor Verde, q",
    sku: "CCDP-2027-010",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-capa-dura-caderno-de-anotacoes",
    name: "Café com Deus Pai vol. 7 (capa dura) + caderno de anotações",
    priceCents: 10490,
    price: "R$104,90",
    originalPrice: null,
    installment: "4 de R$26,23",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-capa-dura-caderno-de-anotacoes-41cc7d.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Neste combo você recebe o livro Café com Deus Pai - Volume 7, na versão capa dura. São 365 novas mensagens, uma para cada dia do ano, para acompanhar sua rotina, fortalecer sua fé e trazer novas perspectivas para os seus dias. Uma jornada de encontros, reflexões e experiências extraordinárias esper",
    sku: "CCDP-2027-011",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-capa-dura-livro-de-oracao-marrom",
    name: "Café com Deus Pai vol. 7 (capa dura) + livro de oração (marrom)",
    priceCents: 12990,
    price: "R$129,90",
    originalPrice: null,
    installment: "4 de R$32,48",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-capa-dura-livro-de-oracao-marrom-dff3cb.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Neste combo você recebe o Café com Deus Pai - Volume 7, na versão capa dura. São 365 novas mensagens, uma para cada dia do ano, para acompanhar sua rotina, fortalecer sua fé e trazer direção para os seus dias. E para complementar esse momento, o combo acompanha o Livro de Oração na cor Marrom, com ",
    sku: "CCDP-2027-012",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-capa-dura-livro-de-oracao-verde",
    name: "Café com Deus Pai vol. 7 (capa dura) + livro de oração (verde)",
    priceCents: 12990,
    price: "R$129,90",
    originalPrice: null,
    installment: "4 de R$32,48",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-capa-dura-livro-de-oracao-verde-da468d.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Neste combo você recebe o Café com Deus Pai - Volume 7, na versão capa dura. São 365 novas mensagens, uma para cada dia do ano, para acompanhar sua rotina, fortalecer sua fé e trazer direção para os seus dias. E para complementar esse momento, o combo acompanha o Livro de Oração na cor Verde, com u",
    sku: "CCDP-2027-013",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-capa-dura-filtro-de-cafe",
    name: "Café com Deus Pai vol. 7 (capa dura) + filtro de café",
    priceCents: 8990,
    price: "R$89,90",
    originalPrice: null,
    installment: "4 de R$22,48",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-capa-dura-filtro-de-cafe-b2f0d2.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Transforme seu momento de leitura em uma experiência ainda mais especial. Neste combo você recebe o livro Café com Deus Pai Volume 7 na versão capa dura. São 365 novas mensagens, uma para cada dia do ano, convidando você a desacelerar, abrir o coração e viver momentos de fé, reflexão e intimidade c",
    sku: "CCDP-2027-014",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-capa-dura-caderno-de-anotacoes-marca-texto",
    name: "Café com Deus Pai vol. 7 (capa dura) + caderno de anotações + marca-texto",
    priceCents: 11490,
    price: "R$114,90",
    originalPrice: null,
    installment: "4 de R$28,73",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-capa-dura-caderno-de-anotacoes-marca-f2c2ed.jpg",
    category: "Lançamento",
    description: "Descrição do Produto O combo inclui o livro Café com Deus Pai - Volume 7, na versão capa dura, o Caderno de Anotações, pensado para registrar aprendizados, reflexões e tudo o que Deus falar com você, além de um marca-texto para destacar mensagens e versículos importantes. Leia, marque e guarde cada aprendizado. Detalhe",
    sku: "CCDP-2027-015",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-capa-dura-livro-de-oracao-marrom-marca-texto-combo577",
    name: "Café com Deus Pai vol. 7 (capa dura) + livro de oração (marrom) + marca-texto",
    priceCents: 13990,
    price: "R$139,90",
    originalPrice: null,
    installment: "4 de R$34,98",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-capa-dura-livro-de-oracao-marrom-mar-79dd1d.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Neste combo você recebe o livro Café com Deus Pai - Volume 7, na versão capa dura. São 365 novas mensagens, uma para cada dia do ano, para acompanhar sua rotina e trazer fé, direção e novas perspectivas para os seus dias. Depois da leitura, continue esse momento com o Livro de Oração na cor Marrom,",
    sku: "CCDP-2027-016",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-capa-dura-livro-de-oracao-verde-marca-texto",
    name: "Café com Deus Pai vol. 7 (capa dura) + livro de oração (verde) + marca-texto",
    priceCents: 13990,
    price: "R$139,90",
    originalPrice: null,
    installment: "4 de R$34,98",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-capa-dura-livro-de-oracao-verde-marc-cfebb8.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Neste combo você recebe o livro Café com Deus Pai - Volume 7, na versão capa dura. São 365 novas mensagens, uma para cada dia do ano, para acompanhar sua rotina e trazer fé, direção e novas perspectivas para os seus dias. Depois da leitura, continue esse momento com o Livro de Oração na cor Verde, ",
    sku: "CCDP-2027-017",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-capa-dura-a-vida-que-voce-busca-esta-na-cura-que-voce-precisa",
    name: "Café com Deus Pai vol. 7 (capa dura) + livro a vida que você busca está na cura que você precisa",
    priceCents: 13490,
    price: "R$134,90",
    originalPrice: null,
    installment: "4 de R$33,73",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-capa-dura-a-vida-que-voce-busca-esta-e0b87c.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Neste combo você recebe o livro Café com Deus Pai - Volume 7, na versão capa dura. São 365 novas mensagens, uma para cada dia do ano, para ajudar você a desacelerar, fortalecer sua fé e viver momentos diários de intimidade com Deus Pai. Você também recebe o livro A Vida que Você Busca Está na Cura ",
    sku: "CCDP-2027-018",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-capa-dura-marca-texto-copo-250ml",
    name: "Café com Deus Pai vol. 7 (capa dura) + marca-texto + copo 250 ml",
    priceCents: 9990,
    price: "R$99,90",
    originalPrice: null,
    installment: "4 de R$24,98",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-capa-dura-marca-texto-copo-250ml-9ee5f7.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Neste combo, você recebe o livro Café com Deus Pai – Volume 7, na versão capa dura, acompanhado de um marca-texto para destacar as mensagens que mais falarem ao seu coração e um copo de 250 ml, produzido em plástico livre de BPA. Seu café, sua leitura e seDetalhes: Autor: Junior Rostirola Editora: ",
    sku: "CCDP-2027-019",
  },
  {
    slug: "cafe-com-deus-pai-kids-tempo-de-crescer",
    name: "Café com Deus Pai Kids: tempo de crescer | edição 2027",
    priceCents: 8990,
    price: "R$89,90",
    originalPrice: null,
    installment: "4 de R$22,48",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-kids-tempo-de-crescer-a5a264.jpg",
    category: "Lançamento",
    description: "Descrição do Produto É tempo de crescer com o Café com Deus Pai Kids! Neste volume, são 365 novas histórias, com novos personagens vivendo aventuras incríveis ao lado de João, Isabella e toda a turma. A cada história, você vai aprender a vencer seus medos, estar mais perto de Deus Pai, ser um bom amigo, cuidar da natur",
    sku: "CCDP-2027-020",
  },
  {
    slug: "cafe-com-deus-pai-teens-aventuras-com-jesus1",
    name: "Café com Deus Pai Teens: aventuras com Jesus | edição 2027",
    priceCents: 8990,
    price: "R$89,90",
    originalPrice: null,
    installment: "4 de R$22,48",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-teens-aventuras-com-jesus1-232fda.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Junior, suas amigas Michelle e Ana, o senhor Antônio e o papagaio Lara vivem grandes aventuras enquanto descobrem como Jesus transformou o mundo com um amor sem igual! Nesta edição você encontrará 365 histórias para acompanhar cada dia do ano e aprender a lidar com os desafios da vida: escola, pass",
    sku: "CCDP-2027-021",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-capa-dura-cafe-com-deus-pai-kids-e-tempo-de-crescer",
    name: "Café com Deus Pai vol. 7 (capa dura) + Café com Deus Pai Kids | é tempo de crescer",
    priceCents: 16990,
    price: "R$169,90",
    originalPrice: null,
    installment: "4 de R$42,48",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-capa-dura-cafe-com-deus-pai-kids-e-t-b82804.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Neste combo você recebe o livro Café com Deus Pai - Volume 7, na versão capa dura. São 365 novas mensagens, uma para cada dia do ano, para ajudar você a desacelerar, fortalecer sua fé e viver momentos diários de intimidade com Deus Pai. Você também recebe o livro Café com Deus Pai Kids - É Tempo de",
    sku: "CCDP-2027-022",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-capa-dura-cafe-com-deus-pai-teens-aventuras-com-jesus",
    name: "Café com Deus Pai vol. 7 (capa dura) + Café com Deus Pai Teens | aventuras com Jesus",
    priceCents: 16990,
    price: "R$169,90",
    originalPrice: null,
    installment: "4 de R$42,48",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-capa-dura-cafe-com-deus-pai-teens-av-e872cc.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Neste combo você recebe o livro Café com Deus Pai - Volume 7, na versão capa dura. São 365 novas mensagens, uma para cada dia do ano, para ajudar você a desacelerar, fortalecer sua fé e viver momentos diários de intimidade com Deus Pai. Você também recebe o livro Café com Deus Pai Teens - Aventuras",
    sku: "CCDP-2027-023",
  },
  {
    slug: "cafe-com-deus-pai-vol-7-capa-dura-livros-de-oracao-verde-e-marrom-caderno-de-anotacoes",
    name: "Café com Deus Pai vol. 7 (capa dura) + livros de oração (verde e marrom) + caderno de anotações",
    priceCents: 20990,
    price: "R$209,90",
    originalPrice: null,
    installment: "4 de R$52,48",
    image: "/sites/cafecomdeuspai-com-8456844d/lancamento-2027/cafe-com-deus-pai-vol-7-capa-dura-livros-de-oracao-verde-e-m-8ff72e.jpg",
    category: "Lançamento",
    description: "Descrição do Produto Neste combo você recebe o livro Café com Deus Pai – Volume 7, na capa dura. São 365 novas mensagens, uma para cada dia do ano, para acompanhar sua rotina e fortalecer sua fé. Para complementar cada devocional, o combo inclui os Livros de Oração Verde e Marrom, que ajudam você a continuar esse momen",
    sku: "CCDP-2027-024",
  },

] as const satisfies readonly CatalogProduct[];

export function getProductBySlug(slug: string): CatalogProduct | undefined {
  return PRODUCTS.find((product) => product.slug === slug);
}
